### ISSUE TITLE
[Bug] ALBUM周期の判定がどんどん先へずれ込んでしまう

### ISSUE THREAD

**Issue by Reviewer-Ranfa** [hizumiaoba/DelesteRandomSelector#29]
残り日数に0を入力した際のバグと思われますが、念の為、全ての入力可能な残り日数を調査し、再現性が取れ次第修正をいたします。

現状の対処法として、JSONファイルを直接書き換える方法がありますが、書き換えを失敗してしまう恐れもあるため、そのままの状態にしておくのがベターだと考えます。

**Comment by hizumiaoba** [comment]
原因を特定
次のバージョンで修正予定

**Comment by hizumiaoba** [comment]
V2.0.3現在、まだ完全な修正に至っていない様子なのでReOpen
